insert into stanowisko (id, nazwa, id_grupa) values (1, 'Social Worker', 621);
insert into stanowisko (id, nazwa, id_grupa) values (2, 'Project Manager', 486);
insert into stanowisko (id, nazwa, id_grupa) values (3, 'Developer I', 361);
insert into stanowisko (id, nazwa, id_grupa) values (4, 'Graphic Designer', 67);
insert into stanowisko (id, nazwa, id_grupa) values (5, 'Recruiting Manager', 587);
insert into stanowisko (id, nazwa, id_grupa) values (6, 'Accountant II', 998);
insert into stanowisko (id, nazwa, id_grupa) values (7, 'Assistant Media Planner', 442);
insert into stanowisko (id, nazwa, id_grupa) values (8, 'Marketing Manager', 865);
insert into stanowisko (id, nazwa, id_grupa) values (9, 'Technical Writer', 566);
insert into stanowisko (id, nazwa, id_grupa) values (10, 'Nuclear Power Engineer', 107);
insert into stanowisko (id, nazwa, id_grupa) values (11, 'Senior Editor', 687);
insert into stanowisko (id, nazwa, id_grupa) values (12, 'Biostatistician IV', 326);
insert into stanowisko (id, nazwa, id_grupa) values (13, 'Payment Adjustment Coordinator', 99);
insert into stanowisko (id, nazwa, id_grupa) values (14, 'Nurse Practicioner', 425);
insert into stanowisko (id, nazwa, id_grupa) values (15, 'Office Assistant IV', 803);
insert into stanowisko (id, nazwa, id_grupa) values (16, 'Programmer Analyst I', 558);
insert into stanowisko (id, nazwa, id_grupa) values (17, 'Health Coach IV', 485);
insert into stanowisko (id, nazwa, id_grupa) values (18, 'Professor', 609);
insert into stanowisko (id, nazwa, id_grupa) values (19, 'Electrical Engineer', 396);
insert into stanowisko (id, nazwa, id_grupa) values (20, 'Cost Accountant', 15);
insert into stanowisko (id, nazwa, id_grupa) values (21, 'Recruiting Manager', 558);
insert into stanowisko (id, nazwa, id_grupa) values (22, 'Graphic Designer', 466);
insert into stanowisko (id, nazwa, id_grupa) values (23, 'Nurse', 892);
insert into stanowisko (id, nazwa, id_grupa) values (24, 'Media Manager II', 413);
insert into stanowisko (id, nazwa, id_grupa) values (25, 'Software Test Engineer III', 469);
insert into stanowisko (id, nazwa, id_grupa) values (26, 'Assistant Professor', 31);
insert into stanowisko (id, nazwa, id_grupa) values (27, 'Civil Engineer', 127);
insert into stanowisko (id, nazwa, id_grupa) values (28, 'Research Associate', 182);
insert into stanowisko (id, nazwa, id_grupa) values (29, 'Safety Technician IV', 934);
insert into stanowisko (id, nazwa, id_grupa) values (30, 'Staff Accountant II', 54);
insert into stanowisko (id, nazwa, id_grupa) values (31, 'Administrative Assistant I', 164);
insert into stanowisko (id, nazwa, id_grupa) values (32, 'Electrical Engineer', 939);
insert into stanowisko (id, nazwa, id_grupa) values (33, 'Biostatistician I', 18);
insert into stanowisko (id, nazwa, id_grupa) values (34, 'Account Coordinator', 1000);
insert into stanowisko (id, nazwa, id_grupa) values (35, 'Health Coach II', 898);
insert into stanowisko (id, nazwa, id_grupa) values (36, 'Project Manager', 224);
insert into stanowisko (id, nazwa, id_grupa) values (37, 'Recruiter', 251);
insert into stanowisko (id, nazwa, id_grupa) values (38, 'Tax Accountant', 167);
insert into stanowisko (id, nazwa, id_grupa) values (39, 'Accounting Assistant II', 854);
insert into stanowisko (id, nazwa, id_grupa) values (40, 'Data Coordinator', 847);
insert into stanowisko (id, nazwa, id_grupa) values (41, 'Programmer Analyst II', 998);
insert into stanowisko (id, nazwa, id_grupa) values (42, 'Financial Advisor', 586);
insert into stanowisko (id, nazwa, id_grupa) values (43, 'Sales Representative', 941);
insert into stanowisko (id, nazwa, id_grupa) values (44, 'Junior Executive', 652);
insert into stanowisko (id, nazwa, id_grupa) values (45, 'Developer I', 60);
insert into stanowisko (id, nazwa, id_grupa) values (46, 'Software Consultant', 219);
insert into stanowisko (id, nazwa, id_grupa) values (47, 'Accountant IV', 705);
insert into stanowisko (id, nazwa, id_grupa) values (48, 'Automation Specialist I', 316);
insert into stanowisko (id, nazwa, id_grupa) values (49, 'Staff Scientist', 731);
insert into stanowisko (id, nazwa, id_grupa) values (50, 'Editor', 73);
insert into stanowisko (id, nazwa, id_grupa) values (51, 'Senior Cost Accountant', 789);
insert into stanowisko (id, nazwa, id_grupa) values (52, 'Staff Scientist', 361);
insert into stanowisko (id, nazwa, id_grupa) values (53, 'Dental Hygienist', 749);
insert into stanowisko (id, nazwa, id_grupa) values (54, 'Software Consultant', 880);
insert into stanowisko (id, nazwa, id_grupa) values (55, 'Operator', 858);
insert into stanowisko (id, nazwa, id_grupa) values (56, 'Food Chemist', 385);
insert into stanowisko (id, nazwa, id_grupa) values (57, 'Quality Control Specialist', 52);
insert into stanowisko (id, nazwa, id_grupa) values (58, 'Environmental Tech', 463);
insert into stanowisko (id, nazwa, id_grupa) values (59, 'Mechanical Systems Engineer', 990);
insert into stanowisko (id, nazwa, id_grupa) values (60, 'Librarian', 492);
insert into stanowisko (id, nazwa, id_grupa) values (61, 'Analog Circuit Design manager', 438);
insert into stanowisko (id, nazwa, id_grupa) values (62, 'Structural Analysis Engineer', 747);
insert into stanowisko (id, nazwa, id_grupa) values (63, 'Social Worker', 303);
insert into stanowisko (id, nazwa, id_grupa) values (64, 'Financial Advisor', 10);
insert into stanowisko (id, nazwa, id_grupa) values (65, 'Community Outreach Specialist', 538);
insert into stanowisko (id, nazwa, id_grupa) values (66, 'Occupational Therapist', 147);
insert into stanowisko (id, nazwa, id_grupa) values (67, 'Sales Representative', 369);
insert into stanowisko (id, nazwa, id_grupa) values (68, 'Business Systems Development Analyst', 906);
insert into stanowisko (id, nazwa, id_grupa) values (69, 'Software Consultant', 321);
insert into stanowisko (id, nazwa, id_grupa) values (70, 'Software Test Engineer II', 722);
insert into stanowisko (id, nazwa, id_grupa) values (71, 'Senior Editor', 574);
insert into stanowisko (id, nazwa, id_grupa) values (72, 'Social Worker', 649);
insert into stanowisko (id, nazwa, id_grupa) values (73, 'Research Assistant IV', 13);
insert into stanowisko (id, nazwa, id_grupa) values (74, 'Executive Secretary', 610);
insert into stanowisko (id, nazwa, id_grupa) values (75, 'Web Developer III', 380);
insert into stanowisko (id, nazwa, id_grupa) values (76, 'Software Test Engineer II', 630);
insert into stanowisko (id, nazwa, id_grupa) values (77, 'Tax Accountant', 343);
insert into stanowisko (id, nazwa, id_grupa) values (78, 'Speech Pathologist', 401);
insert into stanowisko (id, nazwa, id_grupa) values (79, 'Occupational Therapist', 716);
insert into stanowisko (id, nazwa, id_grupa) values (80, 'Accounting Assistant III', 999);
insert into stanowisko (id, nazwa, id_grupa) values (81, 'Quality Control Specialist', 844);
insert into stanowisko (id, nazwa, id_grupa) values (82, 'Analyst Programmer', 3);
insert into stanowisko (id, nazwa, id_grupa) values (83, 'Assistant Manager', 495);
insert into stanowisko (id, nazwa, id_grupa) values (84, 'Product Engineer', 351);
insert into stanowisko (id, nazwa, id_grupa) values (85, 'Biostatistician IV', 198);
insert into stanowisko (id, nazwa, id_grupa) values (86, 'Staff Accountant II', 598);
insert into stanowisko (id, nazwa, id_grupa) values (87, 'Project Manager', 141);
insert into stanowisko (id, nazwa, id_grupa) values (88, 'Accountant III', 47);
insert into stanowisko (id, nazwa, id_grupa) values (89, 'Human Resources Assistant II', 331);
insert into stanowisko (id, nazwa, id_grupa) values (90, 'Financial Advisor', 47);
insert into stanowisko (id, nazwa, id_grupa) values (91, 'Software Consultant', 874);
insert into stanowisko (id, nazwa, id_grupa) values (92, 'Financial Analyst', 407);
insert into stanowisko (id, nazwa, id_grupa) values (93, 'Senior Quality Engineer', 212);
insert into stanowisko (id, nazwa, id_grupa) values (94, 'Assistant Manager', 100);
insert into stanowisko (id, nazwa, id_grupa) values (95, 'GIS Technical Architect', 454);
insert into stanowisko (id, nazwa, id_grupa) values (96, 'Database Administrator II', 866);
insert into stanowisko (id, nazwa, id_grupa) values (97, 'Marketing Assistant', 362);
insert into stanowisko (id, nazwa, id_grupa) values (98, 'Mechanical Systems Engineer', 73);
insert into stanowisko (id, nazwa, id_grupa) values (99, 'Occupational Therapist', 579);
insert into stanowisko (id, nazwa, id_grupa) values (100, 'Research Associate', 874);
insert into stanowisko (id, nazwa, id_grupa) values (101, 'Librarian', 606);
insert into stanowisko (id, nazwa, id_grupa) values (102, 'Sales Associate', 10);
insert into stanowisko (id, nazwa, id_grupa) values (103, 'Paralegal', 577);
insert into stanowisko (id, nazwa, id_grupa) values (104, 'Assistant Manager', 581);
insert into stanowisko (id, nazwa, id_grupa) values (105, 'Assistant Manager', 706);
insert into stanowisko (id, nazwa, id_grupa) values (106, 'Dental Hygienist', 204);
insert into stanowisko (id, nazwa, id_grupa) values (107, 'Community Outreach Specialist', 602);
insert into stanowisko (id, nazwa, id_grupa) values (108, 'Quality Engineer', 122);
insert into stanowisko (id, nazwa, id_grupa) values (109, 'Business Systems Development Analyst', 201);
insert into stanowisko (id, nazwa, id_grupa) values (110, 'Media Manager I', 185);
insert into stanowisko (id, nazwa, id_grupa) values (111, 'Civil Engineer', 785);
insert into stanowisko (id, nazwa, id_grupa) values (112, 'Analog Circuit Design manager', 827);
insert into stanowisko (id, nazwa, id_grupa) values (113, 'Sales Associate', 317);
insert into stanowisko (id, nazwa, id_grupa) values (114, 'Research Nurse', 542);
insert into stanowisko (id, nazwa, id_grupa) values (115, 'Director of Sales', 722);
insert into stanowisko (id, nazwa, id_grupa) values (116, 'Paralegal', 621);
insert into stanowisko (id, nazwa, id_grupa) values (117, 'General Manager', 42);
insert into stanowisko (id, nazwa, id_grupa) values (118, 'Design Engineer', 867);
insert into stanowisko (id, nazwa, id_grupa) values (119, 'Recruiter', 244);
insert into stanowisko (id, nazwa, id_grupa) values (120, 'Tax Accountant', 260);
insert into stanowisko (id, nazwa, id_grupa) values (121, 'Professor', 86);
insert into stanowisko (id, nazwa, id_grupa) values (122, 'Product Engineer', 268);
insert into stanowisko (id, nazwa, id_grupa) values (123, 'Librarian', 58);
insert into stanowisko (id, nazwa, id_grupa) values (124, 'Staff Accountant II', 372);
insert into stanowisko (id, nazwa, id_grupa) values (125, 'Software Consultant', 221);
insert into stanowisko (id, nazwa, id_grupa) values (126, 'Senior Financial Analyst', 746);
insert into stanowisko (id, nazwa, id_grupa) values (127, 'Mechanical Systems Engineer', 167);
insert into stanowisko (id, nazwa, id_grupa) values (128, 'Internal Auditor', 385);
insert into stanowisko (id, nazwa, id_grupa) values (129, 'Automation Specialist I', 732);
insert into stanowisko (id, nazwa, id_grupa) values (130, 'Marketing Assistant', 867);
insert into stanowisko (id, nazwa, id_grupa) values (131, 'Programmer Analyst I', 562);
insert into stanowisko (id, nazwa, id_grupa) values (132, 'Account Executive', 314);
insert into stanowisko (id, nazwa, id_grupa) values (133, 'Operator', 146);
insert into stanowisko (id, nazwa, id_grupa) values (134, 'Chemical Engineer', 385);
insert into stanowisko (id, nazwa, id_grupa) values (135, 'Quality Control Specialist', 355);
insert into stanowisko (id, nazwa, id_grupa) values (136, 'Programmer Analyst III', 915);
insert into stanowisko (id, nazwa, id_grupa) values (137, 'Computer Systems Analyst II', 701);
insert into stanowisko (id, nazwa, id_grupa) values (138, 'Compensation Analyst', 320);
insert into stanowisko (id, nazwa, id_grupa) values (139, 'Business Systems Development Analyst', 561);
insert into stanowisko (id, nazwa, id_grupa) values (140, 'Automation Specialist III', 32);
insert into stanowisko (id, nazwa, id_grupa) values (141, 'Physical Therapy Assistant', 664);
insert into stanowisko (id, nazwa, id_grupa) values (142, 'Safety Technician IV', 604);
insert into stanowisko (id, nazwa, id_grupa) values (143, 'Accountant IV', 4);
insert into stanowisko (id, nazwa, id_grupa) values (144, 'Product Engineer', 44);
insert into stanowisko (id, nazwa, id_grupa) values (145, 'Clinical Specialist', 165);
insert into stanowisko (id, nazwa, id_grupa) values (146, 'Executive Secretary', 495);
insert into stanowisko (id, nazwa, id_grupa) values (147, 'Staff Scientist', 94);
insert into stanowisko (id, nazwa, id_grupa) values (148, 'Human Resources Assistant I', 15);
insert into stanowisko (id, nazwa, id_grupa) values (149, 'Structural Analysis Engineer', 539);
insert into stanowisko (id, nazwa, id_grupa) values (150, 'Financial Analyst', 316);
insert into stanowisko (id, nazwa, id_grupa) values (151, 'Business Systems Development Analyst', 337);
insert into stanowisko (id, nazwa, id_grupa) values (152, 'Nurse', 180);
insert into stanowisko (id, nazwa, id_grupa) values (153, 'VP Sales', 94);
insert into stanowisko (id, nazwa, id_grupa) values (154, 'Data Coordinator', 14);
insert into stanowisko (id, nazwa, id_grupa) values (155, 'Automation Specialist I', 635);
insert into stanowisko (id, nazwa, id_grupa) values (156, 'VP Quality Control', 456);
insert into stanowisko (id, nazwa, id_grupa) values (157, 'Registered Nurse', 365);
insert into stanowisko (id, nazwa, id_grupa) values (158, 'Office Assistant IV', 754);
insert into stanowisko (id, nazwa, id_grupa) values (159, 'Recruiter', 109);
insert into stanowisko (id, nazwa, id_grupa) values (160, 'Research Associate', 93);
insert into stanowisko (id, nazwa, id_grupa) values (161, 'Executive Secretary', 696);
insert into stanowisko (id, nazwa, id_grupa) values (162, 'Payment Adjustment Coordinator', 187);
insert into stanowisko (id, nazwa, id_grupa) values (163, 'Nurse', 501);
insert into stanowisko (id, nazwa, id_grupa) values (164, 'VP Sales', 990);
insert into stanowisko (id, nazwa, id_grupa) values (165, 'Nuclear Power Engineer', 834);
insert into stanowisko (id, nazwa, id_grupa) values (166, 'Senior Editor', 233);
insert into stanowisko (id, nazwa, id_grupa) values (167, 'Operator', 563);
insert into stanowisko (id, nazwa, id_grupa) values (168, 'GIS Technical Architect', 102);
insert into stanowisko (id, nazwa, id_grupa) values (169, 'Account Coordinator', 658);
insert into stanowisko (id, nazwa, id_grupa) values (170, 'Senior Editor', 544);
insert into stanowisko (id, nazwa, id_grupa) values (171, 'Research Associate', 638);
insert into stanowisko (id, nazwa, id_grupa) values (172, 'GIS Technical Architect', 35);
insert into stanowisko (id, nazwa, id_grupa) values (173, 'Web Developer II', 866);
insert into stanowisko (id, nazwa, id_grupa) values (174, 'Business Systems Development Analyst', 97);
insert into stanowisko (id, nazwa, id_grupa) values (175, 'Community Outreach Specialist', 578);
insert into stanowisko (id, nazwa, id_grupa) values (176, 'Programmer Analyst III', 445);
insert into stanowisko (id, nazwa, id_grupa) values (177, 'Dental Hygienist', 676);
insert into stanowisko (id, nazwa, id_grupa) values (178, 'Quality Control Specialist', 880);
insert into stanowisko (id, nazwa, id_grupa) values (179, 'Civil Engineer', 457);
insert into stanowisko (id, nazwa, id_grupa) values (180, 'Software Consultant', 370);
insert into stanowisko (id, nazwa, id_grupa) values (181, 'VP Quality Control', 883);
insert into stanowisko (id, nazwa, id_grupa) values (182, 'Physical Therapy Assistant', 737);
insert into stanowisko (id, nazwa, id_grupa) values (183, 'Budget/Accounting Analyst IV', 232);
insert into stanowisko (id, nazwa, id_grupa) values (184, 'Software Test Engineer I', 898);
insert into stanowisko (id, nazwa, id_grupa) values (185, 'Legal Assistant', 65);
insert into stanowisko (id, nazwa, id_grupa) values (186, 'Assistant Professor', 717);
insert into stanowisko (id, nazwa, id_grupa) values (187, 'Product Engineer', 132);
insert into stanowisko (id, nazwa, id_grupa) values (188, 'Senior Developer', 452);
insert into stanowisko (id, nazwa, id_grupa) values (189, 'Assistant Manager', 407);
insert into stanowisko (id, nazwa, id_grupa) values (190, 'Professor', 403);
insert into stanowisko (id, nazwa, id_grupa) values (191, 'Staff Accountant III', 776);
insert into stanowisko (id, nazwa, id_grupa) values (192, 'Office Assistant I', 452);
insert into stanowisko (id, nazwa, id_grupa) values (193, 'Accounting Assistant II', 929);
insert into stanowisko (id, nazwa, id_grupa) values (194, 'Budget/Accounting Analyst IV', 991);
insert into stanowisko (id, nazwa, id_grupa) values (195, 'Speech Pathologist', 339);
insert into stanowisko (id, nazwa, id_grupa) values (196, 'Senior Editor', 973);
insert into stanowisko (id, nazwa, id_grupa) values (197, 'Nurse Practicioner', 738);
insert into stanowisko (id, nazwa, id_grupa) values (198, 'Research Nurse', 248);
insert into stanowisko (id, nazwa, id_grupa) values (199, 'Environmental Specialist', 195);
insert into stanowisko (id, nazwa, id_grupa) values (200, 'Web Developer IV', 815);
insert into stanowisko (id, nazwa, id_grupa) values (201, 'Budget/Accounting Analyst IV', 107);
insert into stanowisko (id, nazwa, id_grupa) values (202, 'Account Representative II', 176);
insert into stanowisko (id, nazwa, id_grupa) values (203, 'Community Outreach Specialist', 477);
insert into stanowisko (id, nazwa, id_grupa) values (204, 'Programmer Analyst I', 678);
insert into stanowisko (id, nazwa, id_grupa) values (205, 'Paralegal', 991);
insert into stanowisko (id, nazwa, id_grupa) values (206, 'Sales Associate', 558);
insert into stanowisko (id, nazwa, id_grupa) values (207, 'Social Worker', 708);
insert into stanowisko (id, nazwa, id_grupa) values (208, 'Office Assistant II', 951);
insert into stanowisko (id, nazwa, id_grupa) values (209, 'Marketing Manager', 833);
insert into stanowisko (id, nazwa, id_grupa) values (210, 'Human Resources Assistant II', 862);
insert into stanowisko (id, nazwa, id_grupa) values (211, 'Mechanical Systems Engineer', 54);
insert into stanowisko (id, nazwa, id_grupa) values (212, 'Senior Cost Accountant', 547);
insert into stanowisko (id, nazwa, id_grupa) values (213, 'Nurse', 825);
insert into stanowisko (id, nazwa, id_grupa) values (214, 'Research Nurse', 522);
insert into stanowisko (id, nazwa, id_grupa) values (215, 'Nuclear Power Engineer', 48);
insert into stanowisko (id, nazwa, id_grupa) values (216, 'Software Consultant', 528);
insert into stanowisko (id, nazwa, id_grupa) values (217, 'Librarian', 518);
insert into stanowisko (id, nazwa, id_grupa) values (218, 'Environmental Tech', 289);
insert into stanowisko (id, nazwa, id_grupa) values (219, 'Actuary', 368);
insert into stanowisko (id, nazwa, id_grupa) values (220, 'Business Systems Development Analyst', 578);
insert into stanowisko (id, nazwa, id_grupa) values (221, 'Structural Analysis Engineer', 651);
insert into stanowisko (id, nazwa, id_grupa) values (222, 'Geologist IV', 489);
insert into stanowisko (id, nazwa, id_grupa) values (223, 'Internal Auditor', 843);
insert into stanowisko (id, nazwa, id_grupa) values (224, 'Legal Assistant', 116);
insert into stanowisko (id, nazwa, id_grupa) values (225, 'Project Manager', 326);
insert into stanowisko (id, nazwa, id_grupa) values (226, 'Food Chemist', 540);
insert into stanowisko (id, nazwa, id_grupa) values (227, 'Database Administrator I', 82);
insert into stanowisko (id, nazwa, id_grupa) values (228, 'Chemical Engineer', 240);
insert into stanowisko (id, nazwa, id_grupa) values (229, 'Occupational Therapist', 144);
insert into stanowisko (id, nazwa, id_grupa) values (230, 'Office Assistant II', 321);
insert into stanowisko (id, nazwa, id_grupa) values (231, 'Safety Technician I', 368);
insert into stanowisko (id, nazwa, id_grupa) values (232, 'Occupational Therapist', 220);
insert into stanowisko (id, nazwa, id_grupa) values (233, 'Electrical Engineer', 231);
insert into stanowisko (id, nazwa, id_grupa) values (234, 'Analog Circuit Design manager', 712);
insert into stanowisko (id, nazwa, id_grupa) values (235, 'Desktop Support Technician', 239);
insert into stanowisko (id, nazwa, id_grupa) values (236, 'Project Manager', 924);
insert into stanowisko (id, nazwa, id_grupa) values (237, 'GIS Technical Architect', 154);
insert into stanowisko (id, nazwa, id_grupa) values (238, 'Software Test Engineer IV', 279);
insert into stanowisko (id, nazwa, id_grupa) values (239, 'Senior Editor', 184);
insert into stanowisko (id, nazwa, id_grupa) values (240, 'Marketing Assistant', 781);
insert into stanowisko (id, nazwa, id_grupa) values (241, 'Analog Circuit Design manager', 304);
insert into stanowisko (id, nazwa, id_grupa) values (242, 'Administrative Assistant I', 245);
insert into stanowisko (id, nazwa, id_grupa) values (243, 'Office Assistant I', 825);
insert into stanowisko (id, nazwa, id_grupa) values (244, 'Quality Control Specialist', 951);
insert into stanowisko (id, nazwa, id_grupa) values (245, 'Technical Writer', 833);
insert into stanowisko (id, nazwa, id_grupa) values (246, 'Paralegal', 125);
insert into stanowisko (id, nazwa, id_grupa) values (247, 'Sales Representative', 504);
insert into stanowisko (id, nazwa, id_grupa) values (248, 'Automation Specialist I', 453);
insert into stanowisko (id, nazwa, id_grupa) values (249, 'Staff Accountant II', 703);
insert into stanowisko (id, nazwa, id_grupa) values (250, 'VP Sales', 897);
insert into stanowisko (id, nazwa, id_grupa) values (251, 'Project Manager', 164);
insert into stanowisko (id, nazwa, id_grupa) values (252, 'Administrative Assistant III', 966);
insert into stanowisko (id, nazwa, id_grupa) values (253, 'Teacher', 165);
insert into stanowisko (id, nazwa, id_grupa) values (254, 'Assistant Media Planner', 61);
insert into stanowisko (id, nazwa, id_grupa) values (255, 'Programmer IV', 882);
insert into stanowisko (id, nazwa, id_grupa) values (256, 'Product Engineer', 345);
insert into stanowisko (id, nazwa, id_grupa) values (257, 'Programmer II', 134);
insert into stanowisko (id, nazwa, id_grupa) values (258, 'Health Coach III', 897);
insert into stanowisko (id, nazwa, id_grupa) values (259, 'Research Nurse', 133);
insert into stanowisko (id, nazwa, id_grupa) values (260, 'Food Chemist', 368);
insert into stanowisko (id, nazwa, id_grupa) values (261, 'Teacher', 411);
insert into stanowisko (id, nazwa, id_grupa) values (262, 'Project Manager', 813);
insert into stanowisko (id, nazwa, id_grupa) values (263, 'Office Assistant IV', 596);
insert into stanowisko (id, nazwa, id_grupa) values (264, 'Senior Sales Associate', 956);
insert into stanowisko (id, nazwa, id_grupa) values (265, 'Software Test Engineer I', 216);
insert into stanowisko (id, nazwa, id_grupa) values (266, 'Compensation Analyst', 369);
insert into stanowisko (id, nazwa, id_grupa) values (267, 'Nurse Practicioner', 24);
insert into stanowisko (id, nazwa, id_grupa) values (268, 'Food Chemist', 956);
insert into stanowisko (id, nazwa, id_grupa) values (269, 'Operator', 132);
insert into stanowisko (id, nazwa, id_grupa) values (270, 'Professor', 978);
insert into stanowisko (id, nazwa, id_grupa) values (271, 'Director of Sales', 73);
insert into stanowisko (id, nazwa, id_grupa) values (272, 'Tax Accountant', 109);
insert into stanowisko (id, nazwa, id_grupa) values (273, 'Nurse', 885);
insert into stanowisko (id, nazwa, id_grupa) values (274, 'Compensation Analyst', 772);
insert into stanowisko (id, nazwa, id_grupa) values (275, 'Nurse Practicioner', 736);
insert into stanowisko (id, nazwa, id_grupa) values (276, 'Occupational Therapist', 198);
insert into stanowisko (id, nazwa, id_grupa) values (277, 'Staff Accountant IV', 747);
insert into stanowisko (id, nazwa, id_grupa) values (278, 'Compensation Analyst', 619);
insert into stanowisko (id, nazwa, id_grupa) values (279, 'General Manager', 905);
insert into stanowisko (id, nazwa, id_grupa) values (280, 'Senior Sales Associate', 864);
insert into stanowisko (id, nazwa, id_grupa) values (281, 'Health Coach I', 516);
insert into stanowisko (id, nazwa, id_grupa) values (282, 'Automation Specialist III', 784);
insert into stanowisko (id, nazwa, id_grupa) values (283, 'Programmer III', 222);
insert into stanowisko (id, nazwa, id_grupa) values (284, 'Assistant Manager', 603);
insert into stanowisko (id, nazwa, id_grupa) values (285, 'Internal Auditor', 478);
insert into stanowisko (id, nazwa, id_grupa) values (286, 'Assistant Professor', 784);
insert into stanowisko (id, nazwa, id_grupa) values (287, 'Physical Therapy Assistant', 615);
insert into stanowisko (id, nazwa, id_grupa) values (288, 'Nurse', 124);
insert into stanowisko (id, nazwa, id_grupa) values (289, 'General Manager', 602);
insert into stanowisko (id, nazwa, id_grupa) values (290, 'Web Designer IV', 895);
insert into stanowisko (id, nazwa, id_grupa) values (291, 'Social Worker', 12);
insert into stanowisko (id, nazwa, id_grupa) values (292, 'Business Systems Development Analyst', 531);
insert into stanowisko (id, nazwa, id_grupa) values (293, 'Database Administrator IV', 258);
insert into stanowisko (id, nazwa, id_grupa) values (294, 'Sales Representative', 783);
insert into stanowisko (id, nazwa, id_grupa) values (295, 'Clinical Specialist', 502);
insert into stanowisko (id, nazwa, id_grupa) values (296, 'Quality Engineer', 435);
insert into stanowisko (id, nazwa, id_grupa) values (297, 'Human Resources Assistant I', 951);
insert into stanowisko (id, nazwa, id_grupa) values (298, 'General Manager', 878);
insert into stanowisko (id, nazwa, id_grupa) values (299, 'Structural Engineer', 335);
insert into stanowisko (id, nazwa, id_grupa) values (300, 'Information Systems Manager', 775);
insert into stanowisko (id, nazwa, id_grupa) values (301, 'Biostatistician II', 650);
insert into stanowisko (id, nazwa, id_grupa) values (302, 'Research Nurse', 868);
insert into stanowisko (id, nazwa, id_grupa) values (303, 'Analyst Programmer', 874);
insert into stanowisko (id, nazwa, id_grupa) values (304, 'Research Assistant III', 526);
insert into stanowisko (id, nazwa, id_grupa) values (305, 'VP Marketing', 373);
insert into stanowisko (id, nazwa, id_grupa) values (306, 'Design Engineer', 606);
insert into stanowisko (id, nazwa, id_grupa) values (307, 'Senior Financial Analyst', 855);
insert into stanowisko (id, nazwa, id_grupa) values (308, 'Media Manager IV', 153);
insert into stanowisko (id, nazwa, id_grupa) values (309, 'Biostatistician I', 394);
insert into stanowisko (id, nazwa, id_grupa) values (310, 'Paralegal', 34);
insert into stanowisko (id, nazwa, id_grupa) values (311, 'Web Developer III', 131);
insert into stanowisko (id, nazwa, id_grupa) values (312, 'Engineer III', 786);
insert into stanowisko (id, nazwa, id_grupa) values (313, 'Automation Specialist III', 261);
insert into stanowisko (id, nazwa, id_grupa) values (314, 'Help Desk Technician', 953);
insert into stanowisko (id, nazwa, id_grupa) values (315, 'Safety Technician II', 572);
insert into stanowisko (id, nazwa, id_grupa) values (316, 'Speech Pathologist', 999);
insert into stanowisko (id, nazwa, id_grupa) values (317, 'Civil Engineer', 453);
insert into stanowisko (id, nazwa, id_grupa) values (318, 'Physical Therapy Assistant', 465);
insert into stanowisko (id, nazwa, id_grupa) values (319, 'Human Resources Assistant IV', 32);
insert into stanowisko (id, nazwa, id_grupa) values (320, 'Marketing Assistant', 77);
insert into stanowisko (id, nazwa, id_grupa) values (321, 'Speech Pathologist', 864);
insert into stanowisko (id, nazwa, id_grupa) values (322, 'VP Quality Control', 584);
insert into stanowisko (id, nazwa, id_grupa) values (323, 'Dental Hygienist', 410);
insert into stanowisko (id, nazwa, id_grupa) values (324, 'Food Chemist', 312);
insert into stanowisko (id, nazwa, id_grupa) values (325, 'Environmental Tech', 295);
insert into stanowisko (id, nazwa, id_grupa) values (326, 'Geological Engineer', 178);
insert into stanowisko (id, nazwa, id_grupa) values (327, 'Marketing Manager', 37);
insert into stanowisko (id, nazwa, id_grupa) values (328, 'Budget/Accounting Analyst III', 321);
insert into stanowisko (id, nazwa, id_grupa) values (329, 'Professor', 718);
insert into stanowisko (id, nazwa, id_grupa) values (330, 'Food Chemist', 591);
insert into stanowisko (id, nazwa, id_grupa) values (331, 'Registered Nurse', 510);
insert into stanowisko (id, nazwa, id_grupa) values (332, 'Technical Writer', 669);
insert into stanowisko (id, nazwa, id_grupa) values (333, 'Senior Quality Engineer', 545);
insert into stanowisko (id, nazwa, id_grupa) values (334, 'Software Engineer II', 678);
insert into stanowisko (id, nazwa, id_grupa) values (335, 'Civil Engineer', 666);
insert into stanowisko (id, nazwa, id_grupa) values (336, 'Professor', 580);
insert into stanowisko (id, nazwa, id_grupa) values (337, 'Chemical Engineer', 493);
insert into stanowisko (id, nazwa, id_grupa) values (338, 'Staff Scientist', 626);
insert into stanowisko (id, nazwa, id_grupa) values (339, 'Nuclear Power Engineer', 539);
insert into stanowisko (id, nazwa, id_grupa) values (340, 'GIS Technical Architect', 795);
insert into stanowisko (id, nazwa, id_grupa) values (341, 'Assistant Professor', 433);
insert into stanowisko (id, nazwa, id_grupa) values (342, 'Environmental Tech', 216);
insert into stanowisko (id, nazwa, id_grupa) values (343, 'Professor', 874);
insert into stanowisko (id, nazwa, id_grupa) values (344, 'VP Marketing', 360);
insert into stanowisko (id, nazwa, id_grupa) values (345, 'Account Coordinator', 307);
insert into stanowisko (id, nazwa, id_grupa) values (346, 'VP Product Management', 841);
insert into stanowisko (id, nazwa, id_grupa) values (347, 'Food Chemist', 523);
insert into stanowisko (id, nazwa, id_grupa) values (348, 'Marketing Assistant', 682);
insert into stanowisko (id, nazwa, id_grupa) values (349, 'VP Marketing', 574);
insert into stanowisko (id, nazwa, id_grupa) values (350, 'VP Product Management', 649);
insert into stanowisko (id, nazwa, id_grupa) values (351, 'Analyst Programmer', 30);
insert into stanowisko (id, nazwa, id_grupa) values (352, 'Social Worker', 970);
insert into stanowisko (id, nazwa, id_grupa) values (353, 'Accounting Assistant II', 781);
insert into stanowisko (id, nazwa, id_grupa) values (354, 'Analyst Programmer', 694);
insert into stanowisko (id, nazwa, id_grupa) values (355, 'Senior Cost Accountant', 370);
insert into stanowisko (id, nazwa, id_grupa) values (356, 'Sales Representative', 152);
insert into stanowisko (id, nazwa, id_grupa) values (357, 'Teacher', 26);
insert into stanowisko (id, nazwa, id_grupa) values (358, 'Engineer III', 911);
insert into stanowisko (id, nazwa, id_grupa) values (359, 'Structural Engineer', 452);
insert into stanowisko (id, nazwa, id_grupa) values (360, 'Payment Adjustment Coordinator', 228);
insert into stanowisko (id, nazwa, id_grupa) values (361, 'Chemical Engineer', 784);
insert into stanowisko (id, nazwa, id_grupa) values (362, 'Help Desk Operator', 564);
insert into stanowisko (id, nazwa, id_grupa) values (363, 'Operator', 13);
insert into stanowisko (id, nazwa, id_grupa) values (364, 'Assistant Professor', 407);
insert into stanowisko (id, nazwa, id_grupa) values (365, 'Web Developer IV', 410);
insert into stanowisko (id, nazwa, id_grupa) values (366, 'Occupational Therapist', 646);
insert into stanowisko (id, nazwa, id_grupa) values (367, 'Geologist IV', 849);
insert into stanowisko (id, nazwa, id_grupa) values (368, 'Dental Hygienist', 473);
insert into stanowisko (id, nazwa, id_grupa) values (369, 'Assistant Manager', 209);
insert into stanowisko (id, nazwa, id_grupa) values (370, 'Health Coach IV', 657);
insert into stanowisko (id, nazwa, id_grupa) values (371, 'Design Engineer', 750);
insert into stanowisko (id, nazwa, id_grupa) values (372, 'Senior Financial Analyst', 252);
insert into stanowisko (id, nazwa, id_grupa) values (373, 'Accountant IV', 919);
insert into stanowisko (id, nazwa, id_grupa) values (374, 'Data Coordinator', 178);
insert into stanowisko (id, nazwa, id_grupa) values (375, 'Nurse Practicioner', 89);
insert into stanowisko (id, nazwa, id_grupa) values (376, 'Financial Analyst', 164);
insert into stanowisko (id, nazwa, id_grupa) values (377, 'Legal Assistant', 206);
insert into stanowisko (id, nazwa, id_grupa) values (378, 'Assistant Media Planner', 857);
insert into stanowisko (id, nazwa, id_grupa) values (379, 'Product Engineer', 708);
insert into stanowisko (id, nazwa, id_grupa) values (380, 'Web Designer I', 835);
insert into stanowisko (id, nazwa, id_grupa) values (381, 'Speech Pathologist', 967);
insert into stanowisko (id, nazwa, id_grupa) values (382, 'Analyst Programmer', 257);
insert into stanowisko (id, nazwa, id_grupa) values (383, 'Structural Analysis Engineer', 510);
insert into stanowisko (id, nazwa, id_grupa) values (384, 'Structural Analysis Engineer', 311);
insert into stanowisko (id, nazwa, id_grupa) values (385, 'VP Marketing', 563);
insert into stanowisko (id, nazwa, id_grupa) values (386, 'Environmental Tech', 20);
insert into stanowisko (id, nazwa, id_grupa) values (387, 'Teacher', 5);
insert into stanowisko (id, nazwa, id_grupa) values (388, 'Budget/Accounting Analyst IV', 582);
insert into stanowisko (id, nazwa, id_grupa) values (389, 'Product Engineer', 961);
insert into stanowisko (id, nazwa, id_grupa) values (390, 'Structural Analysis Engineer', 599);
insert into stanowisko (id, nazwa, id_grupa) values (391, 'Nurse', 485);
insert into stanowisko (id, nazwa, id_grupa) values (392, 'Project Manager', 585);
insert into stanowisko (id, nazwa, id_grupa) values (393, 'Database Administrator I', 730);
insert into stanowisko (id, nazwa, id_grupa) values (394, 'Junior Executive', 386);
insert into stanowisko (id, nazwa, id_grupa) values (395, 'Electrical Engineer', 191);
insert into stanowisko (id, nazwa, id_grupa) values (396, 'Quality Engineer', 983);
insert into stanowisko (id, nazwa, id_grupa) values (397, 'Software Engineer IV', 265);
insert into stanowisko (id, nazwa, id_grupa) values (398, 'Financial Advisor', 465);
insert into stanowisko (id, nazwa, id_grupa) values (399, 'Teacher', 230);
insert into stanowisko (id, nazwa, id_grupa) values (400, 'Structural Engineer', 883);
insert into stanowisko (id, nazwa, id_grupa) values (401, 'Health Coach II', 97);
insert into stanowisko (id, nazwa, id_grupa) values (402, 'Structural Engineer', 612);
insert into stanowisko (id, nazwa, id_grupa) values (403, 'Safety Technician IV', 4);
insert into stanowisko (id, nazwa, id_grupa) values (404, 'Compensation Analyst', 574);
insert into stanowisko (id, nazwa, id_grupa) values (405, 'Senior Quality Engineer', 736);
insert into stanowisko (id, nazwa, id_grupa) values (406, 'Nurse', 229);
insert into stanowisko (id, nazwa, id_grupa) values (407, 'Junior Executive', 21);
insert into stanowisko (id, nazwa, id_grupa) values (408, 'Environmental Specialist', 560);
insert into stanowisko (id, nazwa, id_grupa) values (409, 'Electrical Engineer', 553);
insert into stanowisko (id, nazwa, id_grupa) values (410, 'Software Consultant', 397);
insert into stanowisko (id, nazwa, id_grupa) values (411, 'Systems Administrator II', 265);
insert into stanowisko (id, nazwa, id_grupa) values (412, 'Biostatistician III', 760);
insert into stanowisko (id, nazwa, id_grupa) values (413, 'Director of Sales', 112);
insert into stanowisko (id, nazwa, id_grupa) values (414, 'Administrative Assistant I', 135);
insert into stanowisko (id, nazwa, id_grupa) values (415, 'Sales Representative', 201);
insert into stanowisko (id, nazwa, id_grupa) values (416, 'Professor', 700);
insert into stanowisko (id, nazwa, id_grupa) values (417, 'Teacher', 190);
insert into stanowisko (id, nazwa, id_grupa) values (418, 'Nurse Practicioner', 677);
insert into stanowisko (id, nazwa, id_grupa) values (419, 'Assistant Professor', 22);
insert into stanowisko (id, nazwa, id_grupa) values (420, 'Electrical Engineer', 298);
insert into stanowisko (id, nazwa, id_grupa) values (421, 'Geologist II', 795);
insert into stanowisko (id, nazwa, id_grupa) values (422, 'Associate Professor', 87);
insert into stanowisko (id, nazwa, id_grupa) values (423, 'Graphic Designer', 673);
insert into stanowisko (id, nazwa, id_grupa) values (424, 'Librarian', 878);
insert into stanowisko (id, nazwa, id_grupa) values (425, 'Occupational Therapist', 531);
insert into stanowisko (id, nazwa, id_grupa) values (426, 'Chemical Engineer', 911);
insert into stanowisko (id, nazwa, id_grupa) values (427, 'Senior Quality Engineer', 632);
insert into stanowisko (id, nazwa, id_grupa) values (428, 'Senior Financial Analyst', 670);
insert into stanowisko (id, nazwa, id_grupa) values (429, 'Marketing Manager', 71);
insert into stanowisko (id, nazwa, id_grupa) values (430, 'Automation Specialist II', 703);
insert into stanowisko (id, nazwa, id_grupa) values (431, 'Systems Administrator I', 728);
insert into stanowisko (id, nazwa, id_grupa) values (432, 'Pharmacist', 105);
insert into stanowisko (id, nazwa, id_grupa) values (433, 'Recruiting Manager', 393);
insert into stanowisko (id, nazwa, id_grupa) values (434, 'VP Sales', 39);
insert into stanowisko (id, nazwa, id_grupa) values (435, 'Office Assistant III', 65);
insert into stanowisko (id, nazwa, id_grupa) values (436, 'Developer III', 142);
insert into stanowisko (id, nazwa, id_grupa) values (437, 'Geologist IV', 789);
insert into stanowisko (id, nazwa, id_grupa) values (438, 'Civil Engineer', 150);
insert into stanowisko (id, nazwa, id_grupa) values (439, 'Recruiter', 44);
insert into stanowisko (id, nazwa, id_grupa) values (440, 'Statistician II', 912);
insert into stanowisko (id, nazwa, id_grupa) values (441, 'Marketing Assistant', 50);
insert into stanowisko (id, nazwa, id_grupa) values (442, 'Marketing Manager', 451);
insert into stanowisko (id, nazwa, id_grupa) values (443, 'Accounting Assistant I', 461);
insert into stanowisko (id, nazwa, id_grupa) values (444, 'Payment Adjustment Coordinator', 871);
insert into stanowisko (id, nazwa, id_grupa) values (445, 'Biostatistician III', 862);
insert into stanowisko (id, nazwa, id_grupa) values (446, 'Registered Nurse', 311);
insert into stanowisko (id, nazwa, id_grupa) values (447, 'Actuary', 560);
insert into stanowisko (id, nazwa, id_grupa) values (448, 'Developer I', 785);
insert into stanowisko (id, nazwa, id_grupa) values (449, 'Administrative Officer', 151);
insert into stanowisko (id, nazwa, id_grupa) values (450, 'Database Administrator I', 261);
insert into stanowisko (id, nazwa, id_grupa) values (451, 'Office Assistant IV', 829);
insert into stanowisko (id, nazwa, id_grupa) values (452, 'Technical Writer', 763);
insert into stanowisko (id, nazwa, id_grupa) values (453, 'Administrative Assistant IV', 598);
insert into stanowisko (id, nazwa, id_grupa) values (454, 'Information Systems Manager', 929);
insert into stanowisko (id, nazwa, id_grupa) values (455, 'Legal Assistant', 666);
insert into stanowisko (id, nazwa, id_grupa) values (456, 'Director of Sales', 217);
insert into stanowisko (id, nazwa, id_grupa) values (457, 'VP Product Management', 170);
insert into stanowisko (id, nazwa, id_grupa) values (458, 'VP Quality Control', 639);
insert into stanowisko (id, nazwa, id_grupa) values (459, 'Software Engineer IV', 87);
insert into stanowisko (id, nazwa, id_grupa) values (460, 'Editor', 968);
insert into stanowisko (id, nazwa, id_grupa) values (461, 'Analog Circuit Design manager', 155);
insert into stanowisko (id, nazwa, id_grupa) values (462, 'Nuclear Power Engineer', 725);
insert into stanowisko (id, nazwa, id_grupa) values (463, 'Assistant Manager', 668);
insert into stanowisko (id, nazwa, id_grupa) values (464, 'Graphic Designer', 398);
insert into stanowisko (id, nazwa, id_grupa) values (465, 'Director of Sales', 967);
insert into stanowisko (id, nazwa, id_grupa) values (466, 'Structural Engineer', 457);
insert into stanowisko (id, nazwa, id_grupa) values (467, 'Mechanical Systems Engineer', 62);
insert into stanowisko (id, nazwa, id_grupa) values (468, 'Structural Analysis Engineer', 442);
insert into stanowisko (id, nazwa, id_grupa) values (469, 'Structural Analysis Engineer', 104);
insert into stanowisko (id, nazwa, id_grupa) values (470, 'Compensation Analyst', 512);
insert into stanowisko (id, nazwa, id_grupa) values (471, 'Social Worker', 187);
insert into stanowisko (id, nazwa, id_grupa) values (472, 'Chemical Engineer', 580);
insert into stanowisko (id, nazwa, id_grupa) values (473, 'Occupational Therapist', 401);
insert into stanowisko (id, nazwa, id_grupa) values (474, 'Financial Advisor', 728);
insert into stanowisko (id, nazwa, id_grupa) values (475, 'Marketing Manager', 668);
insert into stanowisko (id, nazwa, id_grupa) values (476, 'Chief Design Engineer', 285);
insert into stanowisko (id, nazwa, id_grupa) values (477, 'Programmer Analyst I', 636);
insert into stanowisko (id, nazwa, id_grupa) values (478, 'Statistician IV', 357);
insert into stanowisko (id, nazwa, id_grupa) values (479, 'Software Consultant', 764);
insert into stanowisko (id, nazwa, id_grupa) values (480, 'Software Engineer III', 112);
insert into stanowisko (id, nazwa, id_grupa) values (481, 'Actuary', 840);
insert into stanowisko (id, nazwa, id_grupa) values (482, 'Web Developer IV', 481);
insert into stanowisko (id, nazwa, id_grupa) values (483, 'Registered Nurse', 544);
insert into stanowisko (id, nazwa, id_grupa) values (484, 'Community Outreach Specialist', 904);
insert into stanowisko (id, nazwa, id_grupa) values (485, 'Staff Accountant II', 264);
insert into stanowisko (id, nazwa, id_grupa) values (486, 'Quality Engineer', 745);
insert into stanowisko (id, nazwa, id_grupa) values (487, 'Research Nurse', 586);
insert into stanowisko (id, nazwa, id_grupa) values (488, 'Software Test Engineer II', 86);
insert into stanowisko (id, nazwa, id_grupa) values (489, 'Nuclear Power Engineer', 627);
insert into stanowisko (id, nazwa, id_grupa) values (490, 'Payment Adjustment Coordinator', 684);
insert into stanowisko (id, nazwa, id_grupa) values (491, 'Social Worker', 386);
insert into stanowisko (id, nazwa, id_grupa) values (492, 'Marketing Assistant', 727);
insert into stanowisko (id, nazwa, id_grupa) values (493, 'Physical Therapy Assistant', 136);
insert into stanowisko (id, nazwa, id_grupa) values (494, 'Speech Pathologist', 553);
insert into stanowisko (id, nazwa, id_grupa) values (495, 'Analyst Programmer', 754);
insert into stanowisko (id, nazwa, id_grupa) values (496, 'Accountant III', 44);
insert into stanowisko (id, nazwa, id_grupa) values (497, 'Professor', 657);
insert into stanowisko (id, nazwa, id_grupa) values (498, 'Desktop Support Technician', 529);
insert into stanowisko (id, nazwa, id_grupa) values (499, 'Programmer Analyst III', 205);
insert into stanowisko (id, nazwa, id_grupa) values (500, 'Financial Analyst', 988);
insert into stanowisko (id, nazwa, id_grupa) values (501, 'Assistant Media Planner', 528);
insert into stanowisko (id, nazwa, id_grupa) values (502, 'VP Sales', 432);
insert into stanowisko (id, nazwa, id_grupa) values (503, 'Administrative Assistant I', 322);
insert into stanowisko (id, nazwa, id_grupa) values (504, 'Assistant Professor', 438);
insert into stanowisko (id, nazwa, id_grupa) values (505, 'Quality Engineer', 749);
insert into stanowisko (id, nazwa, id_grupa) values (506, 'Tax Accountant', 832);
insert into stanowisko (id, nazwa, id_grupa) values (507, 'Health Coach IV', 85);
insert into stanowisko (id, nazwa, id_grupa) values (508, 'Geological Engineer', 668);
insert into stanowisko (id, nazwa, id_grupa) values (509, 'Software Consultant', 329);
insert into stanowisko (id, nazwa, id_grupa) values (510, 'Food Chemist', 819);
insert into stanowisko (id, nazwa, id_grupa) values (511, 'GIS Technical Architect', 7);
insert into stanowisko (id, nazwa, id_grupa) values (512, 'Senior Editor', 849);
insert into stanowisko (id, nazwa, id_grupa) values (513, 'Assistant Professor', 764);
insert into stanowisko (id, nazwa, id_grupa) values (514, 'VP Quality Control', 135);
insert into stanowisko (id, nazwa, id_grupa) values (515, 'Payment Adjustment Coordinator', 792);
insert into stanowisko (id, nazwa, id_grupa) values (516, 'Tax Accountant', 478);
insert into stanowisko (id, nazwa, id_grupa) values (517, 'Recruiter', 96);
insert into stanowisko (id, nazwa, id_grupa) values (518, 'Engineer IV', 586);
insert into stanowisko (id, nazwa, id_grupa) values (519, 'Environmental Specialist', 33);
insert into stanowisko (id, nazwa, id_grupa) values (520, 'Assistant Media Planner', 140);
insert into stanowisko (id, nazwa, id_grupa) values (521, 'Mechanical Systems Engineer', 262);
insert into stanowisko (id, nazwa, id_grupa) values (522, 'Staff Accountant II', 643);
insert into stanowisko (id, nazwa, id_grupa) values (523, 'Professor', 55);
insert into stanowisko (id, nazwa, id_grupa) values (524, 'Mechanical Systems Engineer', 364);
insert into stanowisko (id, nazwa, id_grupa) values (525, 'Marketing Assistant', 770);
insert into stanowisko (id, nazwa, id_grupa) values (526, 'VP Marketing', 236);
insert into stanowisko (id, nazwa, id_grupa) values (527, 'Computer Systems Analyst IV', 822);
insert into stanowisko (id, nazwa, id_grupa) values (528, 'Account Executive', 145);
insert into stanowisko (id, nazwa, id_grupa) values (529, 'Account Representative III', 826);
insert into stanowisko (id, nazwa, id_grupa) values (530, 'Occupational Therapist', 590);
insert into stanowisko (id, nazwa, id_grupa) values (531, 'VP Sales', 407);
insert into stanowisko (id, nazwa, id_grupa) values (532, 'Biostatistician IV', 400);
insert into stanowisko (id, nazwa, id_grupa) values (533, 'Teacher', 384);
insert into stanowisko (id, nazwa, id_grupa) values (534, 'Account Representative III', 238);
insert into stanowisko (id, nazwa, id_grupa) values (535, 'VP Accounting', 341);
insert into stanowisko (id, nazwa, id_grupa) values (536, 'Assistant Media Planner', 742);
insert into stanowisko (id, nazwa, id_grupa) values (537, 'Research Assistant II', 336);
insert into stanowisko (id, nazwa, id_grupa) values (538, 'Physical Therapy Assistant', 237);
insert into stanowisko (id, nazwa, id_grupa) values (539, 'Web Developer I', 679);
insert into stanowisko (id, nazwa, id_grupa) values (540, 'Research Assistant III', 895);
insert into stanowisko (id, nazwa, id_grupa) values (541, 'Engineer IV', 728);
insert into stanowisko (id, nazwa, id_grupa) values (542, 'Programmer II', 620);
insert into stanowisko (id, nazwa, id_grupa) values (543, 'Senior Sales Associate', 608);
insert into stanowisko (id, nazwa, id_grupa) values (544, 'Web Developer I', 779);
insert into stanowisko (id, nazwa, id_grupa) values (545, 'Sales Representative', 34);
insert into stanowisko (id, nazwa, id_grupa) values (546, 'Systems Administrator IV', 288);
insert into stanowisko (id, nazwa, id_grupa) values (547, 'Associate Professor', 77);
insert into stanowisko (id, nazwa, id_grupa) values (548, 'Marketing Assistant', 638);
insert into stanowisko (id, nazwa, id_grupa) values (549, 'General Manager', 765);
insert into stanowisko (id, nazwa, id_grupa) values (550, 'Database Administrator III', 957);
insert into stanowisko (id, nazwa, id_grupa) values (551, 'Actuary', 923);
insert into stanowisko (id, nazwa, id_grupa) values (552, 'Actuary', 358);
insert into stanowisko (id, nazwa, id_grupa) values (553, 'Recruiter', 134);
insert into stanowisko (id, nazwa, id_grupa) values (554, 'Budget/Accounting Analyst I', 730);
insert into stanowisko (id, nazwa, id_grupa) values (555, 'Data Coordinator', 236);
insert into stanowisko (id, nazwa, id_grupa) values (556, 'Actuary', 855);
insert into stanowisko (id, nazwa, id_grupa) values (557, 'Financial Advisor', 756);
insert into stanowisko (id, nazwa, id_grupa) values (558, 'Administrative Officer', 279);
insert into stanowisko (id, nazwa, id_grupa) values (559, 'Mechanical Systems Engineer', 897);
insert into stanowisko (id, nazwa, id_grupa) values (560, 'Database Administrator I', 109);
insert into stanowisko (id, nazwa, id_grupa) values (561, 'VP Accounting', 585);
insert into stanowisko (id, nazwa, id_grupa) values (562, 'Senior Financial Analyst', 307);
insert into stanowisko (id, nazwa, id_grupa) values (563, 'Geologist IV', 358);
insert into stanowisko (id, nazwa, id_grupa) values (564, 'Technical Writer', 105);
insert into stanowisko (id, nazwa, id_grupa) values (565, 'Project Manager', 715);
insert into stanowisko (id, nazwa, id_grupa) values (566, 'Web Developer I', 821);
insert into stanowisko (id, nazwa, id_grupa) values (567, 'Environmental Specialist', 34);
insert into stanowisko (id, nazwa, id_grupa) values (568, 'Speech Pathologist', 463);
insert into stanowisko (id, nazwa, id_grupa) values (569, 'Clinical Specialist', 29);
insert into stanowisko (id, nazwa, id_grupa) values (570, 'Junior Executive', 612);
insert into stanowisko (id, nazwa, id_grupa) values (571, 'Automation Specialist IV', 494);
insert into stanowisko (id, nazwa, id_grupa) values (572, 'Speech Pathologist', 113);
insert into stanowisko (id, nazwa, id_grupa) values (573, 'Compensation Analyst', 984);
insert into stanowisko (id, nazwa, id_grupa) values (574, 'Marketing Assistant', 20);
insert into stanowisko (id, nazwa, id_grupa) values (575, 'GIS Technical Architect', 973);
insert into stanowisko (id, nazwa, id_grupa) values (576, 'Senior Cost Accountant', 269);
insert into stanowisko (id, nazwa, id_grupa) values (577, 'Assistant Media Planner', 535);
insert into stanowisko (id, nazwa, id_grupa) values (578, 'Senior Editor', 713);
insert into stanowisko (id, nazwa, id_grupa) values (579, 'Structural Engineer', 956);
insert into stanowisko (id, nazwa, id_grupa) values (580, 'Chief Design Engineer', 892);
insert into stanowisko (id, nazwa, id_grupa) values (581, 'Help Desk Technician', 24);
insert into stanowisko (id, nazwa, id_grupa) values (582, 'Senior Quality Engineer', 506);
insert into stanowisko (id, nazwa, id_grupa) values (583, 'Data Coordinator', 377);
insert into stanowisko (id, nazwa, id_grupa) values (584, 'Accountant IV', 488);
insert into stanowisko (id, nazwa, id_grupa) values (585, 'Account Executive', 875);
insert into stanowisko (id, nazwa, id_grupa) values (586, 'Accountant I', 290);
insert into stanowisko (id, nazwa, id_grupa) values (587, 'Senior Developer', 947);
insert into stanowisko (id, nazwa, id_grupa) values (588, 'Registered Nurse', 825);
insert into stanowisko (id, nazwa, id_grupa) values (589, 'Compensation Analyst', 584);
insert into stanowisko (id, nazwa, id_grupa) values (590, 'Accountant III', 838);
insert into stanowisko (id, nazwa, id_grupa) values (591, 'Geological Engineer', 823);
insert into stanowisko (id, nazwa, id_grupa) values (592, 'Professor', 623);
insert into stanowisko (id, nazwa, id_grupa) values (593, 'Technical Writer', 466);
insert into stanowisko (id, nazwa, id_grupa) values (594, 'Cost Accountant', 411);
insert into stanowisko (id, nazwa, id_grupa) values (595, 'Registered Nurse', 632);
insert into stanowisko (id, nazwa, id_grupa) values (596, 'Safety Technician III', 343);
insert into stanowisko (id, nazwa, id_grupa) values (597, 'Internal Auditor', 929);
insert into stanowisko (id, nazwa, id_grupa) values (598, 'VP Accounting', 666);
insert into stanowisko (id, nazwa, id_grupa) values (599, 'Director of Sales', 977);
insert into stanowisko (id, nazwa, id_grupa) values (600, 'Speech Pathologist', 786);
insert into stanowisko (id, nazwa, id_grupa) values (601, 'Administrative Assistant I', 537);
insert into stanowisko (id, nazwa, id_grupa) values (602, 'Environmental Specialist', 410);
insert into stanowisko (id, nazwa, id_grupa) values (603, 'Automation Specialist IV', 959);
insert into stanowisko (id, nazwa, id_grupa) values (604, 'Internal Auditor', 391);
insert into stanowisko (id, nazwa, id_grupa) values (605, 'Teacher', 356);
insert into stanowisko (id, nazwa, id_grupa) values (606, 'Quality Control Specialist', 957);
insert into stanowisko (id, nazwa, id_grupa) values (607, 'Electrical Engineer', 580);
insert into stanowisko (id, nazwa, id_grupa) values (608, 'Recruiting Manager', 393);
insert into stanowisko (id, nazwa, id_grupa) values (609, 'Product Engineer', 470);
insert into stanowisko (id, nazwa, id_grupa) values (610, 'Desktop Support Technician', 559);
insert into stanowisko (id, nazwa, id_grupa) values (611, 'Dental Hygienist', 950);
insert into stanowisko (id, nazwa, id_grupa) values (612, 'Chemical Engineer', 608);
insert into stanowisko (id, nazwa, id_grupa) values (613, 'Software Engineer IV', 820);
insert into stanowisko (id, nazwa, id_grupa) values (614, 'Executive Secretary', 578);
insert into stanowisko (id, nazwa, id_grupa) values (615, 'Registered Nurse', 173);
insert into stanowisko (id, nazwa, id_grupa) values (616, 'Help Desk Operator', 274);
insert into stanowisko (id, nazwa, id_grupa) values (617, 'Paralegal', 555);
insert into stanowisko (id, nazwa, id_grupa) values (618, 'Programmer III', 449);
insert into stanowisko (id, nazwa, id_grupa) values (619, 'Help Desk Operator', 574);
insert into stanowisko (id, nazwa, id_grupa) values (620, 'Research Nurse', 968);
insert into stanowisko (id, nazwa, id_grupa) values (621, 'Web Designer IV', 622);
insert into stanowisko (id, nazwa, id_grupa) values (622, 'Administrative Officer', 112);
insert into stanowisko (id, nazwa, id_grupa) values (623, 'Office Assistant IV', 852);
insert into stanowisko (id, nazwa, id_grupa) values (624, 'Engineer III', 538);
insert into stanowisko (id, nazwa, id_grupa) values (625, 'VP Accounting', 489);
insert into stanowisko (id, nazwa, id_grupa) values (626, 'Administrative Officer', 400);
insert into stanowisko (id, nazwa, id_grupa) values (627, 'Assistant Professor', 886);
insert into stanowisko (id, nazwa, id_grupa) values (628, 'Technical Writer', 412);
insert into stanowisko (id, nazwa, id_grupa) values (629, 'Automation Specialist II', 118);
insert into stanowisko (id, nazwa, id_grupa) values (630, 'Electrical Engineer', 724);
insert into stanowisko (id, nazwa, id_grupa) values (631, 'VP Sales', 583);
insert into stanowisko (id, nazwa, id_grupa) values (632, 'VP Quality Control', 265);
insert into stanowisko (id, nazwa, id_grupa) values (633, 'Senior Cost Accountant', 380);
insert into stanowisko (id, nazwa, id_grupa) values (634, 'Computer Systems Analyst II', 111);
insert into stanowisko (id, nazwa, id_grupa) values (635, 'Design Engineer', 643);
insert into stanowisko (id, nazwa, id_grupa) values (636, 'Tax Accountant', 439);
insert into stanowisko (id, nazwa, id_grupa) values (637, 'Structural Engineer', 634);
insert into stanowisko (id, nazwa, id_grupa) values (638, 'Sales Associate', 43);
insert into stanowisko (id, nazwa, id_grupa) values (639, 'VP Marketing', 672);
insert into stanowisko (id, nazwa, id_grupa) values (640, 'Computer Systems Analyst III', 301);
insert into stanowisko (id, nazwa, id_grupa) values (641, 'Sales Associate', 949);
insert into stanowisko (id, nazwa, id_grupa) values (642, 'Graphic Designer', 461);
insert into stanowisko (id, nazwa, id_grupa) values (643, 'Quality Control Specialist', 47);
insert into stanowisko (id, nazwa, id_grupa) values (644, 'Paralegal', 628);
insert into stanowisko (id, nazwa, id_grupa) values (645, 'Director of Sales', 577);
insert into stanowisko (id, nazwa, id_grupa) values (646, 'Marketing Manager', 969);
insert into stanowisko (id, nazwa, id_grupa) values (647, 'Administrative Assistant IV', 280);
insert into stanowisko (id, nazwa, id_grupa) values (648, 'Web Developer IV', 319);
insert into stanowisko (id, nazwa, id_grupa) values (649, 'Information Systems Manager', 989);
insert into stanowisko (id, nazwa, id_grupa) values (650, 'Dental Hygienist', 934);
insert into stanowisko (id, nazwa, id_grupa) values (651, 'Occupational Therapist', 46);
insert into stanowisko (id, nazwa, id_grupa) values (652, 'Accounting Assistant II', 587);
insert into stanowisko (id, nazwa, id_grupa) values (653, 'Tax Accountant', 328);
insert into stanowisko (id, nazwa, id_grupa) values (654, 'Environmental Specialist', 481);
insert into stanowisko (id, nazwa, id_grupa) values (655, 'Tax Accountant', 351);
insert into stanowisko (id, nazwa, id_grupa) values (656, 'Business Systems Development Analyst', 741);
insert into stanowisko (id, nazwa, id_grupa) values (657, 'Senior Cost Accountant', 251);
insert into stanowisko (id, nazwa, id_grupa) values (658, 'Editor', 84);
insert into stanowisko (id, nazwa, id_grupa) values (659, 'Quality Control Specialist', 392);
insert into stanowisko (id, nazwa, id_grupa) values (660, 'Compensation Analyst', 260);
insert into stanowisko (id, nazwa, id_grupa) values (661, 'Staff Accountant II', 691);
insert into stanowisko (id, nazwa, id_grupa) values (662, 'Senior Financial Analyst', 730);
insert into stanowisko (id, nazwa, id_grupa) values (663, 'General Manager', 353);
insert into stanowisko (id, nazwa, id_grupa) values (664, 'Programmer III', 206);
insert into stanowisko (id, nazwa, id_grupa) values (665, 'Chief Design Engineer', 707);
insert into stanowisko (id, nazwa, id_grupa) values (666, 'Automation Specialist I', 397);
insert into stanowisko (id, nazwa, id_grupa) values (667, 'Structural Analysis Engineer', 806);
insert into stanowisko (id, nazwa, id_grupa) values (668, 'VP Marketing', 181);
insert into stanowisko (id, nazwa, id_grupa) values (669, 'Staff Scientist', 470);
insert into stanowisko (id, nazwa, id_grupa) values (670, 'Systems Administrator I', 246);
insert into stanowisko (id, nazwa, id_grupa) values (671, 'Geological Engineer', 803);
insert into stanowisko (id, nazwa, id_grupa) values (672, 'Software Test Engineer III', 30);
insert into stanowisko (id, nazwa, id_grupa) values (673, 'Senior Sales Associate', 963);
insert into stanowisko (id, nazwa, id_grupa) values (674, 'Programmer Analyst I', 482);
insert into stanowisko (id, nazwa, id_grupa) values (675, 'Sales Representative', 16);
insert into stanowisko (id, nazwa, id_grupa) values (676, 'Senior Quality Engineer', 873);
insert into stanowisko (id, nazwa, id_grupa) values (677, 'Community Outreach Specialist', 225);
insert into stanowisko (id, nazwa, id_grupa) values (678, 'Director of Sales', 71);
insert into stanowisko (id, nazwa, id_grupa) values (679, 'Senior Developer', 156);
insert into stanowisko (id, nazwa, id_grupa) values (680, 'Director of Sales', 824);
insert into stanowisko (id, nazwa, id_grupa) values (681, 'Senior Financial Analyst', 265);
insert into stanowisko (id, nazwa, id_grupa) values (682, 'Editor', 730);
insert into stanowisko (id, nazwa, id_grupa) values (683, 'Chemical Engineer', 356);
insert into stanowisko (id, nazwa, id_grupa) values (684, 'Quality Engineer', 514);
insert into stanowisko (id, nazwa, id_grupa) values (685, 'Marketing Assistant', 181);
insert into stanowisko (id, nazwa, id_grupa) values (686, 'Tax Accountant', 923);
insert into stanowisko (id, nazwa, id_grupa) values (687, 'Human Resources Manager', 624);
insert into stanowisko (id, nazwa, id_grupa) values (688, 'Community Outreach Specialist', 137);
insert into stanowisko (id, nazwa, id_grupa) values (689, 'Mechanical Systems Engineer', 843);
insert into stanowisko (id, nazwa, id_grupa) values (690, 'Cost Accountant', 335);
insert into stanowisko (id, nazwa, id_grupa) values (691, 'Health Coach II', 44);
insert into stanowisko (id, nazwa, id_grupa) values (692, 'VP Sales', 984);
insert into stanowisko (id, nazwa, id_grupa) values (693, 'Web Designer III', 828);
insert into stanowisko (id, nazwa, id_grupa) values (694, 'Structural Engineer', 570);
insert into stanowisko (id, nazwa, id_grupa) values (695, 'Sales Representative', 821);
insert into stanowisko (id, nazwa, id_grupa) values (696, 'Information Systems Manager', 436);
insert into stanowisko (id, nazwa, id_grupa) values (697, 'Assistant Manager', 216);
insert into stanowisko (id, nazwa, id_grupa) values (698, 'VP Quality Control', 680);
insert into stanowisko (id, nazwa, id_grupa) values (699, 'Cost Accountant', 509);
insert into stanowisko (id, nazwa, id_grupa) values (700, 'Food Chemist', 239);
insert into stanowisko (id, nazwa, id_grupa) values (701, 'Tax Accountant', 751);
insert into stanowisko (id, nazwa, id_grupa) values (702, 'Senior Developer', 683);
insert into stanowisko (id, nazwa, id_grupa) values (703, 'Senior Editor', 927);
insert into stanowisko (id, nazwa, id_grupa) values (704, 'Physical Therapy Assistant', 259);
insert into stanowisko (id, nazwa, id_grupa) values (705, 'Civil Engineer', 1000);
insert into stanowisko (id, nazwa, id_grupa) values (706, 'Financial Analyst', 814);
insert into stanowisko (id, nazwa, id_grupa) values (707, 'Mechanical Systems Engineer', 384);
insert into stanowisko (id, nazwa, id_grupa) values (708, 'Chemical Engineer', 91);
insert into stanowisko (id, nazwa, id_grupa) values (709, 'Mechanical Systems Engineer', 77);
insert into stanowisko (id, nazwa, id_grupa) values (710, 'Senior Quality Engineer', 653);
insert into stanowisko (id, nazwa, id_grupa) values (711, 'Sales Representative', 523);
insert into stanowisko (id, nazwa, id_grupa) values (712, 'Software Test Engineer I', 165);
insert into stanowisko (id, nazwa, id_grupa) values (713, 'Clinical Specialist', 320);
insert into stanowisko (id, nazwa, id_grupa) values (714, 'Database Administrator I', 441);
insert into stanowisko (id, nazwa, id_grupa) values (715, 'General Manager', 685);
insert into stanowisko (id, nazwa, id_grupa) values (716, 'Administrative Assistant II', 653);
insert into stanowisko (id, nazwa, id_grupa) values (717, 'Data Coordinator', 788);
insert into stanowisko (id, nazwa, id_grupa) values (718, 'Dental Hygienist', 500);
insert into stanowisko (id, nazwa, id_grupa) values (719, 'Senior Editor', 593);
insert into stanowisko (id, nazwa, id_grupa) values (720, 'Associate Professor', 884);
insert into stanowisko (id, nazwa, id_grupa) values (721, 'Nurse', 988);
insert into stanowisko (id, nazwa, id_grupa) values (722, 'Geologist II', 589);
insert into stanowisko (id, nazwa, id_grupa) values (723, 'Software Consultant', 862);
insert into stanowisko (id, nazwa, id_grupa) values (724, 'Office Assistant I', 167);
insert into stanowisko (id, nazwa, id_grupa) values (725, 'Senior Cost Accountant', 406);
insert into stanowisko (id, nazwa, id_grupa) values (726, 'Information Systems Manager', 884);
insert into stanowisko (id, nazwa, id_grupa) values (727, 'Information Systems Manager', 765);
insert into stanowisko (id, nazwa, id_grupa) values (728, 'Media Manager III', 167);
insert into stanowisko (id, nazwa, id_grupa) values (729, 'Engineer III', 622);
insert into stanowisko (id, nazwa, id_grupa) values (730, 'GIS Technical Architect', 910);
insert into stanowisko (id, nazwa, id_grupa) values (731, 'Pharmacist', 656);
insert into stanowisko (id, nazwa, id_grupa) values (732, 'Technical Writer', 489);
insert into stanowisko (id, nazwa, id_grupa) values (733, 'Teacher', 961);
insert into stanowisko (id, nazwa, id_grupa) values (734, 'Structural Engineer', 343);
insert into stanowisko (id, nazwa, id_grupa) values (735, 'Clinical Specialist', 731);
insert into stanowisko (id, nazwa, id_grupa) values (736, 'Software Engineer III', 71);
insert into stanowisko (id, nazwa, id_grupa) values (737, 'Librarian', 587);
insert into stanowisko (id, nazwa, id_grupa) values (738, 'Account Representative II', 975);
insert into stanowisko (id, nazwa, id_grupa) values (739, 'Executive Secretary', 669);
insert into stanowisko (id, nazwa, id_grupa) values (740, 'Senior Sales Associate', 223);
insert into stanowisko (id, nazwa, id_grupa) values (741, 'Executive Secretary', 759);
insert into stanowisko (id, nazwa, id_grupa) values (742, 'Environmental Specialist', 307);
insert into stanowisko (id, nazwa, id_grupa) values (743, 'Sales Associate', 414);
insert into stanowisko (id, nazwa, id_grupa) values (744, 'Senior Editor', 256);
insert into stanowisko (id, nazwa, id_grupa) values (745, 'Web Designer II', 281);
insert into stanowisko (id, nazwa, id_grupa) values (746, 'Environmental Tech', 458);
insert into stanowisko (id, nazwa, id_grupa) values (747, 'Biostatistician I', 998);
insert into stanowisko (id, nazwa, id_grupa) values (748, 'Information Systems Manager', 711);
insert into stanowisko (id, nazwa, id_grupa) values (749, 'Account Coordinator', 220);
insert into stanowisko (id, nazwa, id_grupa) values (750, 'Recruiting Manager', 177);
insert into stanowisko (id, nazwa, id_grupa) values (751, 'Compensation Analyst', 225);
insert into stanowisko (id, nazwa, id_grupa) values (752, 'Product Engineer', 720);
insert into stanowisko (id, nazwa, id_grupa) values (753, 'Nurse', 501);
insert into stanowisko (id, nazwa, id_grupa) values (754, 'Safety Technician IV', 700);
insert into stanowisko (id, nazwa, id_grupa) values (755, 'Associate Professor', 41);
insert into stanowisko (id, nazwa, id_grupa) values (756, 'Biostatistician IV', 104);
insert into stanowisko (id, nazwa, id_grupa) values (757, 'Software Test Engineer IV', 988);
insert into stanowisko (id, nazwa, id_grupa) values (758, 'Quality Control Specialist', 489);
insert into stanowisko (id, nazwa, id_grupa) values (759, 'Statistician IV', 711);
insert into stanowisko (id, nazwa, id_grupa) values (760, 'Developer III', 573);
insert into stanowisko (id, nazwa, id_grupa) values (761, 'Research Assistant IV', 405);
insert into stanowisko (id, nazwa, id_grupa) values (762, 'Nurse', 206);
insert into stanowisko (id, nazwa, id_grupa) values (763, 'GIS Technical Architect', 505);
insert into stanowisko (id, nazwa, id_grupa) values (764, 'Database Administrator I', 201);
insert into stanowisko (id, nazwa, id_grupa) values (765, 'Automation Specialist II', 188);
insert into stanowisko (id, nazwa, id_grupa) values (766, 'Senior Financial Analyst', 779);
insert into stanowisko (id, nazwa, id_grupa) values (767, 'Compensation Analyst', 914);
insert into stanowisko (id, nazwa, id_grupa) values (768, 'Food Chemist', 569);
insert into stanowisko (id, nazwa, id_grupa) values (769, 'Marketing Manager', 26);
insert into stanowisko (id, nazwa, id_grupa) values (770, 'Chemical Engineer', 576);
insert into stanowisko (id, nazwa, id_grupa) values (771, 'Internal Auditor', 99);
insert into stanowisko (id, nazwa, id_grupa) values (772, 'Recruiting Manager', 55);
insert into stanowisko (id, nazwa, id_grupa) values (773, 'Compensation Analyst', 190);
insert into stanowisko (id, nazwa, id_grupa) values (774, 'Software Test Engineer IV', 14);
insert into stanowisko (id, nazwa, id_grupa) values (775, 'Budget/Accounting Analyst III', 183);
insert into stanowisko (id, nazwa, id_grupa) values (776, 'Environmental Specialist', 906);
insert into stanowisko (id, nazwa, id_grupa) values (777, 'Project Manager', 334);
insert into stanowisko (id, nazwa, id_grupa) values (778, 'Account Executive', 225);
insert into stanowisko (id, nazwa, id_grupa) values (779, 'Speech Pathologist', 471);
insert into stanowisko (id, nazwa, id_grupa) values (780, 'Safety Technician II', 987);
insert into stanowisko (id, nazwa, id_grupa) values (781, 'Design Engineer', 445);
insert into stanowisko (id, nazwa, id_grupa) values (782, 'Graphic Designer', 609);
insert into stanowisko (id, nazwa, id_grupa) values (783, 'Statistician II', 817);
insert into stanowisko (id, nazwa, id_grupa) values (784, 'Business Systems Development Analyst', 152);
insert into stanowisko (id, nazwa, id_grupa) values (785, 'Senior Quality Engineer', 493);
insert into stanowisko (id, nazwa, id_grupa) values (786, 'Developer III', 633);
insert into stanowisko (id, nazwa, id_grupa) values (787, 'Structural Engineer', 831);
insert into stanowisko (id, nazwa, id_grupa) values (788, 'Operator', 568);
insert into stanowisko (id, nazwa, id_grupa) values (789, 'Assistant Manager', 700);
insert into stanowisko (id, nazwa, id_grupa) values (790, 'Data Coordinator', 680);
insert into stanowisko (id, nazwa, id_grupa) values (791, 'Recruiter', 88);
insert into stanowisko (id, nazwa, id_grupa) values (792, 'Associate Professor', 573);
insert into stanowisko (id, nazwa, id_grupa) values (793, 'Compensation Analyst', 883);
insert into stanowisko (id, nazwa, id_grupa) values (794, 'Operator', 960);
insert into stanowisko (id, nazwa, id_grupa) values (795, 'Financial Advisor', 969);
insert into stanowisko (id, nazwa, id_grupa) values (796, 'Data Coordinator', 279);
insert into stanowisko (id, nazwa, id_grupa) values (797, 'Food Chemist', 58);
insert into stanowisko (id, nazwa, id_grupa) values (798, 'Actuary', 704);
insert into stanowisko (id, nazwa, id_grupa) values (799, 'Recruiting Manager', 937);
insert into stanowisko (id, nazwa, id_grupa) values (800, 'Safety Technician IV', 716);
insert into stanowisko (id, nazwa, id_grupa) values (801, 'Accountant III', 563);
insert into stanowisko (id, nazwa, id_grupa) values (802, 'VP Marketing', 12);
insert into stanowisko (id, nazwa, id_grupa) values (803, 'Software Test Engineer IV', 411);
insert into stanowisko (id, nazwa, id_grupa) values (804, 'GIS Technical Architect', 772);
insert into stanowisko (id, nazwa, id_grupa) values (805, 'General Manager', 632);
insert into stanowisko (id, nazwa, id_grupa) values (806, 'Professor', 496);
insert into stanowisko (id, nazwa, id_grupa) values (807, 'Administrative Officer', 674);
insert into stanowisko (id, nazwa, id_grupa) values (808, 'Help Desk Operator', 820);
insert into stanowisko (id, nazwa, id_grupa) values (809, 'Project Manager', 569);
insert into stanowisko (id, nazwa, id_grupa) values (810, 'Food Chemist', 570);
insert into stanowisko (id, nazwa, id_grupa) values (811, 'Junior Executive', 963);
insert into stanowisko (id, nazwa, id_grupa) values (812, 'VP Product Management', 64);
insert into stanowisko (id, nazwa, id_grupa) values (813, 'Senior Developer', 997);
insert into stanowisko (id, nazwa, id_grupa) values (814, 'Librarian', 632);
insert into stanowisko (id, nazwa, id_grupa) values (815, 'Analyst Programmer', 781);
insert into stanowisko (id, nazwa, id_grupa) values (816, 'Legal Assistant', 223);
insert into stanowisko (id, nazwa, id_grupa) values (817, 'Senior Sales Associate', 374);
insert into stanowisko (id, nazwa, id_grupa) values (818, 'Marketing Manager', 355);
insert into stanowisko (id, nazwa, id_grupa) values (819, 'Marketing Assistant', 303);
insert into stanowisko (id, nazwa, id_grupa) values (820, 'Automation Specialist II', 567);
insert into stanowisko (id, nazwa, id_grupa) values (821, 'Director of Sales', 709);
insert into stanowisko (id, nazwa, id_grupa) values (822, 'Compensation Analyst', 588);
insert into stanowisko (id, nazwa, id_grupa) values (823, 'Research Nurse', 193);
insert into stanowisko (id, nazwa, id_grupa) values (824, 'Legal Assistant', 631);
insert into stanowisko (id, nazwa, id_grupa) values (825, 'Sales Associate', 915);
insert into stanowisko (id, nazwa, id_grupa) values (826, 'Research Associate', 183);
insert into stanowisko (id, nazwa, id_grupa) values (827, 'Tax Accountant', 783);
insert into stanowisko (id, nazwa, id_grupa) values (828, 'Programmer I', 879);
insert into stanowisko (id, nazwa, id_grupa) values (829, 'Research Assistant III', 619);
insert into stanowisko (id, nazwa, id_grupa) values (830, 'Analog Circuit Design manager', 208);
insert into stanowisko (id, nazwa, id_grupa) values (831, 'Computer Systems Analyst I', 130);
insert into stanowisko (id, nazwa, id_grupa) values (832, 'Community Outreach Specialist', 405);
insert into stanowisko (id, nazwa, id_grupa) values (833, 'Director of Sales', 45);
insert into stanowisko (id, nazwa, id_grupa) values (834, 'Health Coach IV', 12);
insert into stanowisko (id, nazwa, id_grupa) values (835, 'Budget/Accounting Analyst I', 146);
insert into stanowisko (id, nazwa, id_grupa) values (836, 'Legal Assistant', 911);
insert into stanowisko (id, nazwa, id_grupa) values (837, 'Associate Professor', 852);
insert into stanowisko (id, nazwa, id_grupa) values (838, 'Recruiter', 678);
insert into stanowisko (id, nazwa, id_grupa) values (839, 'Administrative Assistant III', 533);
insert into stanowisko (id, nazwa, id_grupa) values (840, 'Data Coordinator', 328);
insert into stanowisko (id, nazwa, id_grupa) values (841, 'Budget/Accounting Analyst III', 769);
insert into stanowisko (id, nazwa, id_grupa) values (842, 'Assistant Media Planner', 91);
insert into stanowisko (id, nazwa, id_grupa) values (843, 'Nuclear Power Engineer', 999);
insert into stanowisko (id, nazwa, id_grupa) values (844, 'Geologist I', 131);
insert into stanowisko (id, nazwa, id_grupa) values (845, 'Editor', 581);
insert into stanowisko (id, nazwa, id_grupa) values (846, 'Safety Technician III', 73);
insert into stanowisko (id, nazwa, id_grupa) values (847, 'Automation Specialist III', 472);
insert into stanowisko (id, nazwa, id_grupa) values (848, 'Marketing Manager', 393);
insert into stanowisko (id, nazwa, id_grupa) values (849, 'Database Administrator IV', 399);
insert into stanowisko (id, nazwa, id_grupa) values (850, 'Human Resources Assistant I', 8);
insert into stanowisko (id, nazwa, id_grupa) values (851, 'Software Engineer I', 692);
insert into stanowisko (id, nazwa, id_grupa) values (852, 'Chemical Engineer', 996);
insert into stanowisko (id, nazwa, id_grupa) values (853, 'Programmer III', 204);
insert into stanowisko (id, nazwa, id_grupa) values (854, 'Web Developer IV', 844);
insert into stanowisko (id, nazwa, id_grupa) values (855, 'Actuary', 935);
insert into stanowisko (id, nazwa, id_grupa) values (856, 'Budget/Accounting Analyst II', 273);
insert into stanowisko (id, nazwa, id_grupa) values (857, 'Accounting Assistant I', 604);
insert into stanowisko (id, nazwa, id_grupa) values (858, 'Professor', 212);
insert into stanowisko (id, nazwa, id_grupa) values (859, 'Quality Engineer', 668);
insert into stanowisko (id, nazwa, id_grupa) values (860, 'Account Coordinator', 945);
insert into stanowisko (id, nazwa, id_grupa) values (861, 'Associate Professor', 125);
insert into stanowisko (id, nazwa, id_grupa) values (862, 'Dental Hygienist', 383);
insert into stanowisko (id, nazwa, id_grupa) values (863, 'Accountant I', 995);
insert into stanowisko (id, nazwa, id_grupa) values (864, 'Recruiter', 144);
insert into stanowisko (id, nazwa, id_grupa) values (865, 'Help Desk Technician', 446);
insert into stanowisko (id, nazwa, id_grupa) values (866, 'Physical Therapy Assistant', 864);
insert into stanowisko (id, nazwa, id_grupa) values (867, 'Teacher', 530);
insert into stanowisko (id, nazwa, id_grupa) values (868, 'Media Manager III', 54);
insert into stanowisko (id, nazwa, id_grupa) values (869, 'VP Accounting', 519);
insert into stanowisko (id, nazwa, id_grupa) values (870, 'Staff Accountant IV', 375);
insert into stanowisko (id, nazwa, id_grupa) values (871, 'Speech Pathologist', 882);
insert into stanowisko (id, nazwa, id_grupa) values (872, 'Data Coordinator', 661);
insert into stanowisko (id, nazwa, id_grupa) values (873, 'Junior Executive', 802);
insert into stanowisko (id, nazwa, id_grupa) values (874, 'Nuclear Power Engineer', 568);
insert into stanowisko (id, nazwa, id_grupa) values (875, 'Physical Therapy Assistant', 372);
insert into stanowisko (id, nazwa, id_grupa) values (876, 'Dental Hygienist', 386);
insert into stanowisko (id, nazwa, id_grupa) values (877, 'Safety Technician IV', 610);
insert into stanowisko (id, nazwa, id_grupa) values (878, 'Electrical Engineer', 516);
insert into stanowisko (id, nazwa, id_grupa) values (879, 'VP Accounting', 615);
insert into stanowisko (id, nazwa, id_grupa) values (880, 'Computer Systems Analyst III', 371);
insert into stanowisko (id, nazwa, id_grupa) values (881, 'Developer III', 298);
insert into stanowisko (id, nazwa, id_grupa) values (882, 'Business Systems Development Analyst', 1000);
insert into stanowisko (id, nazwa, id_grupa) values (883, 'Research Associate', 391);
insert into stanowisko (id, nazwa, id_grupa) values (884, 'VP Sales', 503);
insert into stanowisko (id, nazwa, id_grupa) values (885, 'VP Product Management', 476);
insert into stanowisko (id, nazwa, id_grupa) values (886, 'Sales Associate', 189);
insert into stanowisko (id, nazwa, id_grupa) values (887, 'Social Worker', 666);
insert into stanowisko (id, nazwa, id_grupa) values (888, 'Editor', 153);
insert into stanowisko (id, nazwa, id_grupa) values (889, 'Dental Hygienist', 835);
insert into stanowisko (id, nazwa, id_grupa) values (890, 'Assistant Professor', 823);
insert into stanowisko (id, nazwa, id_grupa) values (891, 'Editor', 26);
insert into stanowisko (id, nazwa, id_grupa) values (892, 'Community Outreach Specialist', 954);
insert into stanowisko (id, nazwa, id_grupa) values (893, 'Developer II', 508);
insert into stanowisko (id, nazwa, id_grupa) values (894, 'Web Designer III', 754);
insert into stanowisko (id, nazwa, id_grupa) values (895, 'Electrical Engineer', 254);
insert into stanowisko (id, nazwa, id_grupa) values (896, 'Staff Scientist', 182);
insert into stanowisko (id, nazwa, id_grupa) values (897, 'Clinical Specialist', 298);
insert into stanowisko (id, nazwa, id_grupa) values (898, 'Social Worker', 97);
insert into stanowisko (id, nazwa, id_grupa) values (899, 'VP Sales', 735);
insert into stanowisko (id, nazwa, id_grupa) values (900, 'Senior Developer', 584);
insert into stanowisko (id, nazwa, id_grupa) values (901, 'Accountant II', 764);
insert into stanowisko (id, nazwa, id_grupa) values (902, 'Assistant Manager', 714);
insert into stanowisko (id, nazwa, id_grupa) values (903, 'Help Desk Operator', 21);
insert into stanowisko (id, nazwa, id_grupa) values (904, 'Database Administrator I', 634);
insert into stanowisko (id, nazwa, id_grupa) values (905, 'Nuclear Power Engineer', 362);
insert into stanowisko (id, nazwa, id_grupa) values (906, 'Information Systems Manager', 368);
insert into stanowisko (id, nazwa, id_grupa) values (907, 'Programmer I', 91);
insert into stanowisko (id, nazwa, id_grupa) values (908, 'Software Engineer II', 379);
insert into stanowisko (id, nazwa, id_grupa) values (909, 'Environmental Tech', 489);
insert into stanowisko (id, nazwa, id_grupa) values (910, 'Staff Accountant I', 358);
insert into stanowisko (id, nazwa, id_grupa) values (911, 'Quality Control Specialist', 67);
insert into stanowisko (id, nazwa, id_grupa) values (912, 'Electrical Engineer', 26);
insert into stanowisko (id, nazwa, id_grupa) values (913, 'Financial Advisor', 398);
insert into stanowisko (id, nazwa, id_grupa) values (914, 'Electrical Engineer', 646);
insert into stanowisko (id, nazwa, id_grupa) values (915, 'Technical Writer', 996);
insert into stanowisko (id, nazwa, id_grupa) values (916, 'Director of Sales', 57);
insert into stanowisko (id, nazwa, id_grupa) values (917, 'Web Designer I', 783);
insert into stanowisko (id, nazwa, id_grupa) values (918, 'Software Test Engineer III', 611);
insert into stanowisko (id, nazwa, id_grupa) values (919, 'Graphic Designer', 782);
insert into stanowisko (id, nazwa, id_grupa) values (920, 'Quality Control Specialist', 263);
insert into stanowisko (id, nazwa, id_grupa) values (921, 'Teacher', 805);
insert into stanowisko (id, nazwa, id_grupa) values (922, 'Chemical Engineer', 920);
insert into stanowisko (id, nazwa, id_grupa) values (923, 'Assistant Professor', 453);
insert into stanowisko (id, nazwa, id_grupa) values (924, 'Programmer II', 3);
insert into stanowisko (id, nazwa, id_grupa) values (925, 'Staff Scientist', 166);
insert into stanowisko (id, nazwa, id_grupa) values (926, 'VP Sales', 548);
insert into stanowisko (id, nazwa, id_grupa) values (927, 'Financial Advisor', 694);
insert into stanowisko (id, nazwa, id_grupa) values (928, 'Staff Accountant I', 229);
insert into stanowisko (id, nazwa, id_grupa) values (929, 'Senior Developer', 350);
insert into stanowisko (id, nazwa, id_grupa) values (930, 'Sales Associate', 200);
insert into stanowisko (id, nazwa, id_grupa) values (931, 'Automation Specialist I', 707);
insert into stanowisko (id, nazwa, id_grupa) values (932, 'Professor', 433);
insert into stanowisko (id, nazwa, id_grupa) values (933, 'Payment Adjustment Coordinator', 604);
insert into stanowisko (id, nazwa, id_grupa) values (934, 'Internal Auditor', 202);
insert into stanowisko (id, nazwa, id_grupa) values (935, 'Human Resources Assistant III', 545);
insert into stanowisko (id, nazwa, id_grupa) values (936, 'Operator', 46);
insert into stanowisko (id, nazwa, id_grupa) values (937, 'Sales Representative', 539);
insert into stanowisko (id, nazwa, id_grupa) values (938, 'Analog Circuit Design manager', 478);
insert into stanowisko (id, nazwa, id_grupa) values (939, 'Occupational Therapist', 724);
insert into stanowisko (id, nazwa, id_grupa) values (940, 'Electrical Engineer', 375);
insert into stanowisko (id, nazwa, id_grupa) values (941, 'Software Test Engineer II', 500);
insert into stanowisko (id, nazwa, id_grupa) values (942, 'Dental Hygienist', 735);
insert into stanowisko (id, nazwa, id_grupa) values (943, 'VP Accounting', 798);
insert into stanowisko (id, nazwa, id_grupa) values (944, 'Junior Executive', 976);
insert into stanowisko (id, nazwa, id_grupa) values (945, 'Human Resources Assistant I', 56);
insert into stanowisko (id, nazwa, id_grupa) values (946, 'VP Sales', 785);
insert into stanowisko (id, nazwa, id_grupa) values (947, 'Compensation Analyst', 68);
insert into stanowisko (id, nazwa, id_grupa) values (948, 'Financial Advisor', 874);
insert into stanowisko (id, nazwa, id_grupa) values (949, 'Analog Circuit Design manager', 855);
insert into stanowisko (id, nazwa, id_grupa) values (950, 'Social Worker', 256);
insert into stanowisko (id, nazwa, id_grupa) values (951, 'Professor', 737);
insert into stanowisko (id, nazwa, id_grupa) values (952, 'Technical Writer', 918);
insert into stanowisko (id, nazwa, id_grupa) values (953, 'Actuary', 505);
insert into stanowisko (id, nazwa, id_grupa) values (954, 'Legal Assistant', 454);
insert into stanowisko (id, nazwa, id_grupa) values (955, 'Design Engineer', 670);
insert into stanowisko (id, nazwa, id_grupa) values (956, 'Media Manager IV', 797);
insert into stanowisko (id, nazwa, id_grupa) values (957, 'Senior Developer', 643);
insert into stanowisko (id, nazwa, id_grupa) values (958, 'Administrative Officer', 248);
insert into stanowisko (id, nazwa, id_grupa) values (959, 'Chemical Engineer', 315);
insert into stanowisko (id, nazwa, id_grupa) values (960, 'Editor', 651);
insert into stanowisko (id, nazwa, id_grupa) values (961, 'Structural Engineer', 951);
insert into stanowisko (id, nazwa, id_grupa) values (962, 'Help Desk Operator', 128);
insert into stanowisko (id, nazwa, id_grupa) values (963, 'Civil Engineer', 422);
insert into stanowisko (id, nazwa, id_grupa) values (964, 'Junior Executive', 341);
insert into stanowisko (id, nazwa, id_grupa) values (965, 'Actuary', 787);
insert into stanowisko (id, nazwa, id_grupa) values (966, 'Project Manager', 959);
insert into stanowisko (id, nazwa, id_grupa) values (967, 'Help Desk Operator', 634);
insert into stanowisko (id, nazwa, id_grupa) values (968, 'Programmer Analyst II', 970);
insert into stanowisko (id, nazwa, id_grupa) values (969, 'Software Consultant', 548);
insert into stanowisko (id, nazwa, id_grupa) values (970, 'Environmental Tech', 391);
insert into stanowisko (id, nazwa, id_grupa) values (971, 'Occupational Therapist', 895);
insert into stanowisko (id, nazwa, id_grupa) values (972, 'Senior Editor', 275);
insert into stanowisko (id, nazwa, id_grupa) values (973, 'Media Manager I', 446);
insert into stanowisko (id, nazwa, id_grupa) values (974, 'Clinical Specialist', 972);
insert into stanowisko (id, nazwa, id_grupa) values (975, 'Analog Circuit Design manager', 871);
insert into stanowisko (id, nazwa, id_grupa) values (976, 'Pharmacist', 236);
insert into stanowisko (id, nazwa, id_grupa) values (977, 'Assistant Manager', 902);
insert into stanowisko (id, nazwa, id_grupa) values (978, 'Design Engineer', 990);
insert into stanowisko (id, nazwa, id_grupa) values (979, 'Geological Engineer', 843);
insert into stanowisko (id, nazwa, id_grupa) values (980, 'Biostatistician IV', 958);
insert into stanowisko (id, nazwa, id_grupa) values (981, 'Assistant Manager', 437);
insert into stanowisko (id, nazwa, id_grupa) values (982, 'Nuclear Power Engineer', 417);
insert into stanowisko (id, nazwa, id_grupa) values (983, 'Nuclear Power Engineer', 179);
insert into stanowisko (id, nazwa, id_grupa) values (984, 'Civil Engineer', 416);
insert into stanowisko (id, nazwa, id_grupa) values (985, 'Geological Engineer', 21);
insert into stanowisko (id, nazwa, id_grupa) values (986, 'Assistant Media Planner', 889);
insert into stanowisko (id, nazwa, id_grupa) values (987, 'Financial Advisor', 225);
insert into stanowisko (id, nazwa, id_grupa) values (988, 'Assistant Manager', 458);
insert into stanowisko (id, nazwa, id_grupa) values (989, 'Senior Financial Analyst', 503);
insert into stanowisko (id, nazwa, id_grupa) values (990, 'VP Marketing', 875);
insert into stanowisko (id, nazwa, id_grupa) values (991, 'Research Assistant II', 162);
insert into stanowisko (id, nazwa, id_grupa) values (992, 'Web Designer II', 128);
insert into stanowisko (id, nazwa, id_grupa) values (993, 'Sales Representative', 960);
insert into stanowisko (id, nazwa, id_grupa) values (994, 'Environmental Specialist', 414);
insert into stanowisko (id, nazwa, id_grupa) values (995, 'Administrative Officer', 987);
insert into stanowisko (id, nazwa, id_grupa) values (996, 'Developer IV', 116);
insert into stanowisko (id, nazwa, id_grupa) values (997, 'Analog Circuit Design manager', 464);
insert into stanowisko (id, nazwa, id_grupa) values (998, 'Accounting Assistant III', 980);
insert into stanowisko (id, nazwa, id_grupa) values (999, 'Nuclear Power Engineer', 812);
insert into stanowisko (id, nazwa, id_grupa) values (1000, 'Research Assistant II', 465);
